"""Reads the committed price book projection.

`nodus quote` answers "what would this brief cost, here and on prices anyone can
check". That is a pre-purchase question, so it is answered without a control
plane and without a network: the book is a committed artifact generated by
`./bin/pricebook publish`, and this module reads it.

The arithmetic here deliberately reproduces what the publisher already computed
rather than inventing a second method. For the brief the book was captured for,
`quote()` returns the committed sheets untouched. For any other brief it
recomputes with the same formula, which the committed numbers can be used to
verify:

    cost to complete = rate/h  x  declared hours  x  performance factor

    AWS H100-80:  $6.88 x 12h x 0.45  = $37.152   (matches the committed sheet)
    breakeven:    $6.88 / $3.430881   = 2.0053x   (matches breakeven_speedup_x)

The performance factor is the one input that is a judgement rather than a
citation, and it is carried through labelled so every surface can say so.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# Search order for the book, most explicit first. The env var exists so the
# demo can be pointed at a re-published book without editing anything; the
# repo-relative path is what makes `nodus quote` work from a checkout with no
# configuration at all.
ENV_VAR = "NODUS_PRICEBOOK"
_REPO_DEFAULT = Path(__file__).resolve().parents[3] / "apps/landing/src/_data/baselineSpread.json"


class PricebookMissing(Exception):
    """Raised when no book could be found. Carries the paths that were tried."""


@dataclass(frozen=True)
class Rate:
    seller: str
    sku: str
    fit_class: str
    device_memory_gb: float
    usd_per_gpu_hour: float
    tier: str
    quoted_usd_hour: float
    gpus_per_unit: int
    normalization: str
    source_url: str
    as_of: str = ""
    retrieved_at: str = ""
    label: str = ""

    @property
    def interruptible(self) -> bool:
        return self.tier != "on_demand"

    @property
    def derivation(self) -> str:
        """How the per-GPU number was reached, for surfaces that show their work.

        A whole-instance price reported as a per-GPU rate is the one arithmetic
        error in this domain that destroys an argument on contact, so the
        division is carried around rather than left implicit.
        """
        if self.gpus_per_unit and self.gpus_per_unit > 1:
            return f"{self.quoted_usd_hour:.6f} / {self.gpus_per_unit}"
        return "as listed, per GPU-hour"


@dataclass(frozen=True)
class SellerQuote:
    seller: str
    picks: str
    cost_usd: float
    rate_usd_hour: float
    hours: float
    breakeven_speedup_x: float
    per_fit: dict[str, float] = field(default_factory=dict)


@dataclass(frozen=True)
class Book:
    as_of: str
    captured_at: str
    generated_by: str
    measured: bool
    reference_brief: dict[str, Any]
    rates: list[Rate]
    assumptions: list[dict[str, Any]]
    caveats: list[str]
    breakeven_span: dict[str, Any]
    _sheets: list[dict[str, Any]]
    source_path: Path

    def perf_factor(self, fit_class: str) -> tuple[float, str]:
        """Runtime multiplier for a fit class, and the basis it rests on.

        Matches on the key's *subject* only — the part between "perf." and the
        first "." after it. Keys name both sides of a comparison
        ("perf.H100-80.vs.A100-80"), so a substring test finds A100 inside the
        H100 row and silently prices an A100 as if it ran at H100 speed. That
        bug is invisible in the cost column, which comes from the committed
        sheet, and shows up only in the hours — which is exactly the kind of
        wrong number that survives a review.

        Returns 1.0/"definition" for anything the book carries no assumption
        about: an unknown part is assumed no faster than the baseline rather
        than optimistically scaled.
        """
        want = fit_class.upper()
        for a in self.assumptions:
            key = str(a.get("key", ""))
            if not key.startswith("perf."):
                continue
            subject = key[len("perf."):].split(".", 1)[0].upper()
            if subject == want or subject.split("-", 1)[0] == want:
                return float(a.get("value") or 1.0), str(a.get("basis") or "assumed")
        return 1.0, "definition"

    def assumed_keys(self) -> list[dict[str, Any]]:
        return [a for a in self.assumptions if str(a.get("basis")) == "assumed"]

    def sellers(self) -> list[str]:
        # Order preserved from the book so two surfaces list them alike.
        seen: list[str] = []
        for r in self.rates:
            if r.seller not in seen:
                seen.append(r.seller)
        return seen


def _rate(d: dict[str, Any]) -> Rate:
    return Rate(
        seller=str(d.get("seller") or ""),
        sku=str(d.get("sku") or ""),
        fit_class=str(d.get("fit_class") or ""),
        device_memory_gb=float(d.get("device_memory_gb") or 0.0),
        usd_per_gpu_hour=float(d.get("usd_per_gpu_hour") or 0.0),
        tier=str(d.get("tier") or "on_demand"),
        quoted_usd_hour=float(d.get("quoted_usd_hour") or 0.0),
        gpus_per_unit=int(d.get("gpus_per_unit") or 1),
        normalization=str(d.get("normalization") or ""),
        source_url=str(d.get("source_url") or ""),
        as_of=str(d.get("as_of") or ""),
        retrieved_at=str(d.get("retrieved_at") or ""),
        label=str(d.get("label") or ""),
    )


def load(path: str | os.PathLike[str] | None = None) -> Book:
    """Find and parse the book. Raises PricebookMissing listing what was tried.

    An explicitly named book that does not exist is an error, not a reason to
    look elsewhere. Falling back to the committed default would answer a
    question about one price book with numbers from another, and the caller
    would have no way to tell from the output which one they got.
    """
    if path is not None:
        p = Path(path).expanduser()
        if not p.is_file():
            raise PricebookMissing(f"no price book at {p}")
        return _parse(p)

    tried: list[Path] = []
    for cand in (os.environ.get(ENV_VAR), _REPO_DEFAULT):
        if not cand:
            continue
        p = Path(cand).expanduser()
        tried.append(p)
        if p.is_file():
            return _parse(p)
    raise PricebookMissing("no price book found; tried: " + ", ".join(str(t) for t in tried))


def _parse(p: Path) -> Book:
    d = json.loads(p.read_text())
    return Book(
        as_of=str(d.get("as_of") or ""),
        captured_at=str(d.get("captured_at") or ""),
        generated_by=str(d.get("generated_by") or ""),
        measured=bool(d.get("measured", False)),
        reference_brief=dict(d.get("reference_brief") or {}),
        rates=[_rate(r) for r in d.get("rates") or []],
        assumptions=list(d.get("assumptions") or []),
        caveats=list(d.get("caveats") or []),
        breakeven_span=dict(d.get("breakeven_span") or {}),
        _sheets=list(d.get("sheets") or []),
        source_path=p,
    )


def matches_reference(book: Book, peak_memory_gb: float, hours: float) -> bool:
    ref = book.reference_brief
    return (
        abs(float(ref.get("peak_memory_gb") or 0) - peak_memory_gb) < 1e-9
        and abs(float(ref.get("expected_runtime_hours") or 0) - hours) < 1e-9
    )


def quote(book: Book, peak_memory_gb: float, hours: float, *, on_demand_only: bool = True) -> list[SellerQuote]:
    """Cost to complete this brief on each seller's published list.

    When the brief is the one the book was captured for, the committed sheets
    are returned rather than recomputed — the published artifact is the
    authority on its own reference case, and recomputing it would let a
    rounding difference put two numbers on screen that should be one.
    """
    if matches_reference(book, peak_memory_gb, hours) and book._sheets:
        out: list[SellerQuote] = []
        for s in book._sheets:
            picks = str(s.get("router_picks") or "")
            per_fit = {
                "A100": float(s.get("a100_cost_to_complete_usd") or 0.0),
                "H100": float(s.get("h100_cost_to_complete_usd") or 0.0),
            }
            rate_key = "h100_usd_per_gpu_hour" if picks.upper().startswith("H100") else "a100_usd_per_gpu_hour"
            rate = float(s.get(rate_key) or 0.0)
            cost = per_fit.get(picks.upper(), min(v for v in per_fit.values() if v > 0))
            perf, _ = book.perf_factor(picks)
            out.append(SellerQuote(
                seller=str(s.get("seller") or ""),
                picks=picks,
                cost_usd=cost,
                rate_usd_hour=rate,
                hours=hours * perf,
                breakeven_speedup_x=float(s.get("breakeven_speedup_x") or 0.0),
                per_fit=per_fit,
            ))
        return out

    # A brief the book was not captured for. Same formula, stated in the module
    # docstring and checkable against the committed sheets.
    by_seller: dict[str, list[Rate]] = {}
    for r in book.rates:
        if on_demand_only and r.interruptible:
            continue
        if r.device_memory_gb + 1e-9 < peak_memory_gb:
            continue
        by_seller.setdefault(r.seller, []).append(r)

    out = []
    for seller, rates in by_seller.items():
        costed = []
        for r in rates:
            perf, _ = book.perf_factor(r.fit_class)
            costed.append((r.usd_per_gpu_hour * hours * perf, r, perf))
        if not costed:
            continue
        costed.sort(key=lambda t: t[0])
        best_cost, best, best_perf = costed[0]
        # Breakeven only means something with two parts to trade off.
        be = 0.0
        if len(costed) > 1:
            alt = costed[1][1]
            if best.usd_per_gpu_hour > 0 and alt.usd_per_gpu_hour > 0:
                hi, lo = sorted((best.usd_per_gpu_hour, alt.usd_per_gpu_hour), reverse=True)
                be = hi / lo
        out.append(SellerQuote(
            seller=seller,
            picks=best.fit_class,
            cost_usd=best_cost,
            rate_usd_hour=best.usd_per_gpu_hour,
            hours=hours * best_perf,
            breakeven_speedup_x=be,
            per_fit={r.fit_class: c for c, r, _ in costed},
        ))
    out.sort(key=lambda q: q.cost_usd)
    return out
